### ISSUE TITLE
Current vtk writer cannot handle large mesh size

### ISSUE THREAD

**Issue by prashjha** [nonlocalmodels/NLMech#29]
## Expected Behavior

Handle large mesh and write node and cell data.

## Actual Behavior

Vtk writer fails when writing mesh with nodes >= 1443001 and triangle elements >= 2880000.

## Steps to Reproduce the Problem

Try generating uniform mesh using tools/mesh with input file below

```yaml
Output: 
  Path: .
  Mesh: mesh
Domain: [0.000000e+00, 0.000000e+00, 1.200000e-01, 3.000000e-02]
Horizon: 2.000000e-04
Horizon_h_Ratio: 4
Mesh_Type: uniform_tri
```

## Specifications

Please describe your environment

  - HPX Version: 1.1.0
  - Platform (compiler, OS): Ubuntu 18.04/Ubuntu 16.04
